# Generated by Django 4.2.7 on 2023-12-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='month',
        ),
        migrations.RemoveField(
            model_name='month',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
