# Generated by Django 4.2.5 on 2023-10-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_involvedpersons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='involvedPersons',
        ),
        migrations.AddField(
            model_name='appointment',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
